"""
Data Preparation Module for LightGBM Meal Ranker

Purpose:
    This module handles downloading, loading, cleaning, and validating the Food.com 
    Recipes and Interactions dataset used for training the meal recommendation model.

Key Responsibilities:
    - Download Food.com dataset from Kaggle API (if not cached locally)
    - Load and parse recipes CSV with nutritional information
    - Load and parse user-recipe interactions CSV with ratings
    - Extract and infer cuisine types from recipe metadata
    - Classify recipes into meal slots (breakfast, lunch, dinner, snack)
    - Validate nutritional data (non-negative macros, required fields)
    - Export cleaned data for use by train.py

Dependencies:
    - kaggle: For dataset download
    - pandas: For data loading and manipulation
    - numpy: For numerical validation

Expected Input:
    - Kaggle API credentials configured at ~/.kaggle/kaggle.json
    - Dataset: food-com-recipes-and-user-interactions

Expected Output:
    - data/RAW_recipes_cleaned.csv: Validated recipes with inferred metadata
    - data/RAW_interactions_cleaned.csv: User interaction data

Usage:
    python data_prep.py

Author: Generated by Kiro AI
Date: 2024
"""

import os
import sys
import zipfile
import pandas as pd
import numpy as np
from pathlib import Path
from typing import Dict, List, Any


def download_dataset() -> None:
    """
    Download the Food.com Recipes and Interactions dataset from Kaggle.
    
    Uses the Kaggle API to download the dataset. If the dataset already exists locally,
    this function skips the download to avoid unnecessary API calls.
    
    Prerequisites:
        - Kaggle API credentials must be configured at ~/.kaggle/kaggle.json
        - User must have accepted the dataset's terms on Kaggle website
    
    Output:
        Downloads and extracts the dataset to ./data/ directory
        
    Raises:
        OSError: If Kaggle credentials are not found
        Exception: If download fails
    """
    # Check if Kaggle credentials exist
    kaggle_config_path = Path.home() / '.kaggle' / 'kaggle.json'
    if not kaggle_config_path.exists():
        raise OSError(
            "Kaggle API credentials not found. Please configure at ~/.kaggle/kaggle.json\n"
            "Visit https://www.kaggle.com/docs/api for setup instructions."
        )
    
    # Create data directory if it doesn't exist
    data_dir = Path('./data')
    data_dir.mkdir(exist_ok=True)
    
    # Check if dataset already exists locally
    recipes_file = data_dir / 'RAW_recipes.csv'
    interactions_file = data_dir / 'RAW_interactions.csv'
    
    if recipes_file.exists() and interactions_file.exists():
        print("Dataset already exists locally. Skipping download.")
        return
    
    print("Downloading Food.com dataset from Kaggle...")
    
    try:
        # Import kaggle here to provide better error messages if not installed
        from kaggle.api.kaggle_api_extended import KaggleApi
        
        # Initialize and authenticate Kaggle API
        api = KaggleApi()
        api.authenticate()
        
        # Download the dataset
        # Dataset identifier: shuyangli94/food-com-recipes-and-user-interactions
        dataset_name = 'shuyangli94/food-com-recipes-and-user-interactions'
        print(f"Downloading {dataset_name}...")
        api.dataset_download_files(dataset_name, path=str(data_dir), unzip=True)
        
        print(f"Dataset downloaded and extracted to {data_dir}/")
        
    except ImportError:
        raise ImportError(
            "Kaggle package not installed. Install it with: pip install kaggle"
        )
    except Exception as e:
        raise Exception(f"Failed to download dataset: {str(e)}")


def load_recipes(path: str) -> pd.DataFrame:
    """
    Load and validate the recipes CSV file.
    
    Reads the Food.com recipes CSV and validates that all required columns are present
    and contain valid data types. The recipes dataset includes recipe metadata, 
    ingredients, and nutritional information.
    
    Args:
        path: File path to the recipes CSV file
        
    Returns:
        DataFrame with validated recipe data including columns:
        - id: Recipe identifier
        - name: Recipe name
        - tags: List of recipe tags
        - nutrition: List of nutritional values [calories, total_fat, sugar, sodium, protein, saturated_fat, carbohydrates]
        - ingredients: List of ingredient strings
        
    Raises:
        FileNotFoundError: If the CSV file doesn't exist
        ValueError: If required columns are missing
    """
    # Check if file exists
    if not os.path.exists(path):
        raise FileNotFoundError(f"Recipes file not found at: {path}")
    
    print(f"Loading recipes from {path}...")
    
    # Load CSV file
    df = pd.read_csv(path)
    
    # Validate required columns exist
    required_columns = ['id', 'name', 'tags', 'nutrition', 'ingredients']
    missing_columns = [col for col in required_columns if col not in df.columns]
    
    if missing_columns:
        raise ValueError(f"Missing required columns: {missing_columns}")
    
    print(f"Loaded {len(df)} recipes successfully.")
    
    # Parse string representations of lists (tags, nutrition, ingredients)
    # The CSV stores these as string representations like "['item1', 'item2']"
    import ast
    
    print("Parsing list columns (tags, nutrition, ingredients)...")
    df['tags'] = df['tags'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
    df['nutrition'] = df['nutrition'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
    df['ingredients'] = df['ingredients'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
    
    return df


def infer_cuisine_type(recipe: Dict[str, Any]) -> str:
    """
    Extract or infer cuisine type from recipe metadata.
    
    Analyzes recipe tags and name to determine the cuisine type. Uses keyword matching
    to identify cuisines like italian, mexican, chinese, indian, etc. Falls back to
    'american' as the default if no cuisine can be inferred.
    
    Args:
        recipe: Dictionary containing recipe data with 'tags' and 'name' keys
        
    Returns:
        Cuisine type string (lowercase), e.g., 'italian', 'mexican', 'chinese'
        Defaults to 'american' if no cuisine can be determined
    """
    # Define cuisine keywords to search for in tags and recipe name
    cuisine_keywords = {
        'italian': ['italian', 'pasta', 'pizza', 'risotto', 'tuscany', 'sicilian'],
        'mexican': ['mexican', 'taco', 'burrito', 'enchilada', 'salsa', 'tex-mex'],
        'chinese': ['chinese', 'stir-fry', 'wok', 'szechuan', 'cantonese'],
        'indian': ['indian', 'curry', 'tandoori', 'masala', 'biryani'],
        'japanese': ['japanese', 'sushi', 'teriyaki', 'ramen', 'tempura'],
        'french': ['french', 'provence', 'crepe', 'croissant', 'baguette'],
        'thai': ['thai', 'pad-thai', 'coconut-curry'],
        'greek': ['greek', 'mediterranean', 'gyro', 'tzatziki', 'feta'],
        'spanish': ['spanish', 'paella', 'tapas', 'chorizo'],
        'middle-eastern': ['middle-eastern', 'hummus', 'falafel', 'shawarma', 'lebanese'],
        'korean': ['korean', 'kimchi', 'bulgogi', 'bibimbap'],
        'vietnamese': ['vietnamese', 'pho', 'banh-mi'],
    }
    
    # Get tags and name from recipe, convert to lowercase for matching
    tags = recipe.get('tags', [])
    tags_lower = [str(tag).lower() for tag in tags]
    name_lower = str(recipe.get('name', '')).lower()
    
    # Check each cuisine type for keyword matches
    for cuisine, keywords in cuisine_keywords.items():
        for keyword in keywords:
            # Check if keyword appears in any tag
            if any(keyword in tag for tag in tags_lower):
                return cuisine
            # Check if keyword appears in recipe name
            if keyword in name_lower:
                return cuisine
    
    # Default to 'american' if no specific cuisine identified
    return 'american'


def infer_meal_slot(recipe: Dict[str, Any]) -> str:
    """
    Classify recipe into a meal slot (breakfast, lunch, dinner, or snack).
    
    Uses recipe tags and name to determine the most appropriate meal slot.
    Breakfast items are identified by keywords like 'breakfast', 'brunch', 'morning'.
    Snacks are identified by size indicators and specific tags.
    Otherwise, defaults to 'dinner' (most common meal slot).
    
    Args:
        recipe: Dictionary containing recipe data with 'tags' and 'name' keys
        
    Returns:
        Meal slot string: 'breakfast', 'lunch', 'dinner', or 'snack'
    """
    # Get tags and name from recipe, convert to lowercase
    tags = recipe.get('tags', [])
    tags_lower = [str(tag).lower() for tag in tags]
    name_lower = str(recipe.get('name', '')).lower()
    
    # Combine tags and name for keyword matching
    search_text = ' '.join(tags_lower) + ' ' + name_lower
    
    # Breakfast keywords have highest priority
    breakfast_keywords = ['breakfast', 'brunch', 'morning', 'cereal', 'pancake', 
                          'waffle', 'oatmeal', 'french-toast', 'breakfast-bread']
    if any(keyword in search_text for keyword in breakfast_keywords):
        return 'breakfast'
    
    # Snack keywords
    snack_keywords = ['snack', 'appetizer', 'finger-food', 'bar-cookie', 
                     'candy', 'dip', 'spread', 'small-plate', 'bite-size']
    if any(keyword in search_text for keyword in snack_keywords):
        return 'snack'
    
    # Lunch keywords (less common, many recipes work for both lunch and dinner)
    lunch_keywords = ['lunch', 'sandwich', 'wrap', 'salad']
    if any(keyword in search_text for keyword in lunch_keywords):
        return 'lunch'
    
    # Default to dinner (most recipes are suitable for dinner)
    return 'dinner'


def validate_nutrition(df: pd.DataFrame) -> pd.DataFrame:
    """
    Validate nutritional data and ensure all macros are non-negative.
    
    Checks that all nutritional values are present and non-negative. The nutrition
    column contains a list of 7 values: [calories, total_fat, sugar, sodium, 
    protein, saturated_fat, carbohydrates].
    
    This function extracts these values into separate columns, validates they are
    non-negative, and removes any rows with invalid nutritional data.
    
    Args:
        df: DataFrame with 'nutrition' column containing list of nutritional values
        
    Returns:
        DataFrame with validated nutrition data and new columns:
        - calories: Numeric, non-negative
        - total_fat_g: Numeric, non-negative  
        - sugar_g: Numeric, non-negative
        - sodium_mg: Numeric, non-negative
        - protein_g: Numeric, non-negative
        - saturated_fat_g: Numeric, non-negative
        - carbs_g: Numeric, non-negative
    """
    print("Validating nutritional data...")
    
    initial_count = len(df)
    
    # Extract nutrition values from the list
    # Format: [calories, total_fat, sugar, sodium, protein, saturated_fat, carbohydrates]
    # Note: Percentages of Daily Value (PDV) in original data, we'll use as absolute values
    df['calories'] = df['nutrition'].apply(lambda x: float(x[0]) if len(x) > 0 else np.nan)
    df['total_fat_g'] = df['nutrition'].apply(lambda x: float(x[1]) if len(x) > 1 else np.nan)
    df['sugar_g'] = df['nutrition'].apply(lambda x: float(x[2]) if len(x) > 2 else np.nan)
    df['sodium_mg'] = df['nutrition'].apply(lambda x: float(x[3]) if len(x) > 3 else np.nan)
    df['protein_g'] = df['nutrition'].apply(lambda x: float(x[4]) if len(x) > 4 else np.nan)
    df['saturated_fat_g'] = df['nutrition'].apply(lambda x: float(x[5]) if len(x) > 5 else np.nan)
    df['carbs_g'] = df['nutrition'].apply(lambda x: float(x[6]) if len(x) > 6 else np.nan)
    
    # Check for missing nutritional values
    df = df.dropna(subset=['calories', 'total_fat_g', 'protein_g', 'carbs_g'])
    
    # Validate non-negative values for all macro nutrients
    # Assert that all values are >= 0
    nutrition_columns = ['calories', 'total_fat_g', 'sugar_g', 'sodium_mg', 
                        'protein_g', 'saturated_fat_g', 'carbs_g']
    
    for col in nutrition_columns:
        if col in df.columns:
            # Remove rows with negative values
            negative_mask = df[col] < 0
            negative_count = negative_mask.sum()
            if negative_count > 0:
                print(f"Warning: Found {negative_count} recipes with negative {col}. Removing them.")
                df = df[~negative_mask]
    
    removed_count = initial_count - len(df)
    print(f"Validation complete. Removed {removed_count} recipes with invalid nutrition data.")
    print(f"Remaining recipes: {len(df)}")
    
    return df


def main():
    """
    Main execution function for data preparation pipeline.
    
    Orchestrates the complete data preparation workflow:
    1. Download dataset from Kaggle (if needed)
    2. Load recipes CSV
    3. Infer cuisine types for all recipes
    4. Classify recipes into meal slots
    5. Validate nutritional data
    6. Export cleaned data
    """
    print("=" * 60)
    print("Food.com Data Preparation Pipeline")
    print("=" * 60)
    
    try:
        # Step 1: Download dataset from Kaggle
        download_dataset()
        
        # Step 2: Load recipes CSV
        recipes_path = './data/RAW_recipes.csv'
        df = load_recipes(recipes_path)
        
        # Step 3: Infer cuisine type for each recipe
        print("\nInferring cuisine types...")
        df['cuisine_type'] = df.apply(
            lambda row: infer_cuisine_type(row.to_dict()), 
            axis=1
        )
        print(f"Cuisine distribution:\n{df['cuisine_type'].value_counts()}")
        
        # Step 4: Infer meal slot for each recipe
        print("\nClassifying recipes into meal slots...")
        df['meal_slot'] = df.apply(
            lambda row: infer_meal_slot(row.to_dict()), 
            axis=1
        )
        print(f"Meal slot distribution:\n{df['meal_slot'].value_counts()}")
        
        # Step 5: Validate nutritional data
        df = validate_nutrition(df)
        
        # Step 6: Export cleaned data
        output_path = './data/RAW_recipes_cleaned.csv'
        print(f"\nSaving cleaned recipes to {output_path}...")
        df.to_csv(output_path, index=False)
        print(f"Successfully saved {len(df)} cleaned recipes.")
        
        # Also copy interactions file if it exists (no processing needed for interactions)
        interactions_path = './data/RAW_interactions.csv'
        if os.path.exists(interactions_path):
            output_interactions_path = './data/RAW_interactions_cleaned.csv'
            print(f"\nCopying interactions data to {output_interactions_path}...")
            interactions_df = pd.read_csv(interactions_path)
            interactions_df.to_csv(output_interactions_path, index=False)
            print(f"Successfully copied {len(interactions_df)} interaction records.")
        
        print("\n" + "=" * 60)
        print("Data preparation complete!")
        print("=" * 60)
        
    except Exception as e:
        print(f"\nError during data preparation: {str(e)}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
