"""
Model Training Module for LightGBM Meal Ranker

Purpose:
    This module implements the complete training pipeline for the LightGBM-based
    meal recommendation model, including feature engineering, model training,
    evaluation, and serialization.

Key Responsibilities:
    - Load cleaned recipe and interaction data from data_prep.py
    - Simulate diverse synthetic user profiles (age, weight, height, activity, goals)
    - Compute user macro targets (TDEE, protein, carbs, fat) from profiles
    - Simulate remaining macros (random consumption throughout the day)
    - Engineer 7 features for (user, meal) pairs:
        * macro_delta_calories: |meal.calories - remaining.calories|
        * macro_delta_protein: |meal.protein - remaining.protein|
        * macro_delta_carbs: |meal.carbs - remaining.carbs|
        * macro_delta_fat: |meal.fat - remaining.fat|
        * cuisine_match: 1 if meal.cuisine == user.cuisine_pref else 0
        * meal_slot_match: 1 if meal.slot == requested_slot else 0
        * days_since_last_eaten: recency signal (999 if never eaten)
    - Create (user, meal) training pairs with recipe ratings as labels
    - Train LGBMRegressor model
    - Evaluate model performance (NDCG@5, Precision@5, MAE)
    - Serialize trained model to meal_ranker.txt
    - Save feature schema and training metrics

Dependencies:
    - lightgbm: For model training
    - pandas: For data manipulation
    - numpy: For numerical operations
    - scikit-learn: For train/test split and metrics

Expected Input:
    - data/RAW_recipes_cleaned.csv (from data_prep.py)
    - data/RAW_interactions_cleaned.csv (from data_prep.py)

Expected Output:
    - meal_ranker.txt: Serialized LightGBM model
    - feature_schema.json: Feature names, order, types, and ranges
    - training_metrics.json: NDCG@5, Precision@5, MAE baseline

Usage:
    python train.py                          # Train on Food.com dataset only
    python train.py --use-production-logs    # Include production feedback data

Author: Generated by Kiro AI
Date: 2024
"""

import numpy as np
import pandas as pd
from typing import Dict, Any, Tuple, List
import random
import json
import os
import sys
import argparse
from pathlib import Path
from datetime import datetime
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, ndcg_score
import lightgbm as lgb


def simulate_user_profiles(n: int = 10000) -> pd.DataFrame:
    """
    Generate synthetic user profiles with diverse characteristics.
    
    Simulates realistic user populations with varying:
    - Age: 18-80 years
    - Weight: 50-150 kg
    - Height: 150-200 cm
    - Activity levels: sedentary, lightly_active, moderately_active, very_active, extra_active
    - Goals: weight_loss, maintenance, muscle_gain
    
    Args:
        n: Number of synthetic user profiles to generate
        
    Returns:
        DataFrame with columns: user_id, age, weight_kg, height_cm, activity_level, goal
    """
    np.random.seed(42)  # For reproducibility
    random.seed(42)
    
    activity_levels = [
        'sedentary',          # Little to no exercise
        'lightly_active',     # Light exercise 1-3 days/week
        'moderately_active',  # Moderate exercise 3-5 days/week
        'very_active',        # Hard exercise 6-7 days/week
        'extra_active'        # Very hard exercise & physical job
    ]
    
    goals = [
        'weight_loss',   # Caloric deficit
        'maintenance',   # Caloric maintenance
        'muscle_gain'    # Caloric surplus
    ]
    
    profiles = []
    
    for i in range(n):
        # Age distribution: normal distribution centered at 35, std 15, clipped to 18-80
        age = int(np.clip(np.random.normal(35, 15), 18, 80))
        
        # Weight distribution: normal distribution centered at 75kg, std 20, clipped to 50-150
        weight_kg = float(np.clip(np.random.normal(75, 20), 50, 150))
        
        # Height distribution: normal distribution centered at 170cm, std 12, clipped to 150-200
        height_cm = float(np.clip(np.random.normal(170, 12), 150, 200))
        
        # Activity level: weighted distribution (more sedentary and moderately active)
        activity_weights = [0.30, 0.25, 0.25, 0.15, 0.05]
        activity_level = random.choices(activity_levels, weights=activity_weights, k=1)[0]
        
        # Goal: weighted distribution (more weight loss and maintenance)
        goal_weights = [0.45, 0.40, 0.15]
        goal = random.choices(goals, weights=goal_weights, k=1)[0]
        
        profiles.append({
            'user_id': f'user_{i}',
            'age': age,
            'weight_kg': round(weight_kg, 1),
            'height_cm': round(height_cm, 1),
            'activity_level': activity_level,
            'goal': goal
        })
    
    return pd.DataFrame(profiles)


def compute_tdee(profile: Dict[str, Any]) -> float:
    """
    Calculate Total Daily Energy Expenditure using Mifflin-St Jeor equation.
    
    TDEE = BMR × Activity Multiplier
    BMR (Basal Metabolic Rate) = 10 × weight(kg) + 6.25 × height(cm) - 5 × age(years) + s
    where s = +5 for males, -161 for females (we'll use average: -78)
    
    Activity Multipliers:
    - sedentary: 1.2
    - lightly_active: 1.375
    - moderately_active: 1.55
    - very_active: 1.725
    - extra_active: 1.9
    
    Args:
        profile: Dictionary with keys: age, weight_kg, height_cm, activity_level
        
    Returns:
        Total Daily Energy Expenditure in calories
    """
    # Mifflin-St Jeor BMR calculation (using averaged gender constant)
    bmr = (10 * profile['weight_kg'] + 
           6.25 * profile['height_cm'] - 
           5 * profile['age'] - 78)
    
    # Activity multipliers
    activity_multipliers = {
        'sedentary': 1.2,
        'lightly_active': 1.375,
        'moderately_active': 1.55,
        'very_active': 1.725,
        'extra_active': 1.9
    }
    
    multiplier = activity_multipliers.get(profile['activity_level'], 1.55)
    tdee = bmr * multiplier
    
    return round(tdee, 1)


def compute_macro_targets(profile: Dict[str, Any], tdee: float) -> Dict[str, float]:
    """
    Calculate daily protein, carbs, and fat targets based on TDEE and goal.
    
    Macro Distribution Strategy:
    - Weight Loss: High protein, moderate carbs, moderate fat (deficit: -500 cal)
      * Protein: 2.0g/kg bodyweight (higher to preserve muscle)
      * Fat: 25% of calories
      * Carbs: remainder
      
    - Maintenance: Balanced macros
      * Protein: 1.6g/kg bodyweight
      * Fat: 30% of calories
      * Carbs: remainder
      
    - Muscle Gain: High protein, high carbs, moderate fat (surplus: +300 cal)
      * Protein: 2.2g/kg bodyweight (higher for muscle synthesis)
      * Fat: 25% of calories
      * Carbs: remainder
    
    Calorie Adjustments:
    - Weight Loss: TDEE - 500
    - Maintenance: TDEE
    - Muscle Gain: TDEE + 300
    
    Args:
        profile: Dictionary with keys: weight_kg, goal
        tdee: Total Daily Energy Expenditure in calories
        
    Returns:
        Dictionary with keys: calories, protein_g, carbs_g, fat_g
    """
    weight_kg = profile['weight_kg']
    goal = profile['goal']
    
    # Adjust calories based on goal
    if goal == 'weight_loss':
        target_calories = tdee - 500
        protein_per_kg = 2.0
        fat_percentage = 0.25
    elif goal == 'muscle_gain':
        target_calories = tdee + 300
        protein_per_kg = 2.2
        fat_percentage = 0.25
    else:  # maintenance
        target_calories = tdee
        protein_per_kg = 1.6
        fat_percentage = 0.30
    
    # Calculate protein target (g/kg bodyweight)
    protein_g = weight_kg * protein_per_kg
    protein_calories = protein_g * 4  # 4 calories per gram of protein
    
    # Calculate fat target (percentage of total calories)
    fat_calories = target_calories * fat_percentage
    fat_g = fat_calories / 9  # 9 calories per gram of fat
    
    # Calculate carbs (remainder after protein and fat)
    carbs_calories = target_calories - protein_calories - fat_calories
    carbs_g = carbs_calories / 4  # 4 calories per gram of carbs
    
    return {
        'calories': round(target_calories, 1),
        'protein_g': round(protein_g, 1),
        'carbs_g': round(max(0, carbs_g), 1),  # Ensure non-negative
        'fat_g': round(fat_g, 1)
    }


def simulate_remaining_macros(targets: Dict[str, float]) -> Dict[str, float]:
    """
    Simulate remaining macros by generating random consumption (0-100% of targets).
    
    This simulates a user at various points throughout their day:
    - Early morning: 90-100% remaining (little consumed)
    - Mid-day: 40-70% remaining (some meals logged)
    - Evening: 10-40% remaining (most meals logged)
    
    We use a beta distribution to create realistic consumption patterns.
    
    Args:
        targets: Dictionary with keys: calories, protein_g, carbs_g, fat_g
        
    Returns:
        Dictionary with remaining amounts for: calories, protein_g, carbs_g, fat_g
    """
    # Beta distribution creates realistic consumption patterns
    # alpha=2, beta=2 gives a bell curve centered at 50%
    # alpha=2, beta=5 skews towards lower consumption (early day)
    # alpha=5, beta=2 skews towards higher consumption (late day)
    
    # Mix of time-of-day scenarios
    scenario = random.choice(['early', 'mid', 'late'])
    
    if scenario == 'early':
        # Early day: 80-100% remaining
        consumption_pct = np.random.beta(2, 8)  # Skewed towards low consumption
    elif scenario == 'mid':
        # Mid-day: 30-70% remaining
        consumption_pct = np.random.beta(5, 5)  # Centered around 50%
    else:  # late
        # Late day: 0-30% remaining
        consumption_pct = np.random.beta(8, 2)  # Skewed towards high consumption
    
    # Calculate remaining for each macro (add some variation per macro)
    remaining = {}
    for key in ['calories', 'protein_g', 'carbs_g', 'fat_g']:
        # Add ±10% variation per macro to simulate realistic uneven consumption
        macro_variation = np.random.uniform(0.9, 1.1)
        remaining_pct = 1 - (consumption_pct * macro_variation)
        remaining_pct = np.clip(remaining_pct, 0, 1)  # Ensure 0-100%
        
        remaining[key] = round(targets[key] * remaining_pct, 1)
    
    return remaining


def simulate_cuisine_preference() -> str:
    """
    Randomly assign a cuisine preference type.
    
    Cuisine types should match those available in the meals table.
    Distribution is weighted to reflect popularity.
    
    Returns:
        Cuisine type string
    """
    cuisines = [
        'american',
        'italian',
        'mexican',
        'asian',
        'indian',
        'mediterranean',
        'french',
        'chinese',
        'japanese',
        'thai',
        None  # No preference
    ]
    
    # Weighted distribution (more common cuisines have higher weights)
    weights = [0.15, 0.15, 0.12, 0.10, 0.08, 0.10, 0.05, 0.08, 0.06, 0.06, 0.05]
    
    return random.choices(cuisines, weights=weights, k=1)[0]


def simulate_meal_slot_request() -> str:
    """
    Simulate a meal slot request with realistic distributions.
    
    Realistic distribution:
    - Breakfast: 25%
    - Lunch: 30%
    - Dinner: 35%
    - Snack: 10%
    
    Returns:
        Meal slot string: 'breakfast', 'lunch', 'dinner', or 'snack'
    """
    meal_slots = ['breakfast', 'lunch', 'dinner', 'snack']
    weights = [0.25, 0.30, 0.35, 0.10]
    
    return random.choices(meal_slots, weights=weights, k=1)[0]


# =============================================================================
# Feature Engineering Functions
# =============================================================================

def compute_macro_delta(meal: Dict[str, Any], remaining: Dict[str, float]) -> list:
    """
    Compute macro delta features: absolute difference between meal and remaining macros.
    
    This is the PRIMARY feature for meal ranking. It captures how well a meal "fits"
    the user's remaining nutritional needs for the day.
    
    Rationale:
    - Small deltas = meal closely matches remaining needs (GOOD fit)
    - Large deltas = meal overshoots or undershoots needs (POOR fit)
    - Absolute values ensure we penalize both overshooting and undershooting
    
    Example:
    - User has 500 calories remaining
    - Meal A: 480 calories → delta = 20 (excellent fit)
    - Meal B: 800 calories → delta = 300 (poor fit, too much)
    - Meal C: 200 calories → delta = 300 (poor fit, too little)
    
    Args:
        meal: Dictionary with keys: calories, protein_g, carbs_g, fat_g
        remaining: Dictionary with keys: calories, protein_g, carbs_g, fat_g
        
    Returns:
        List of 4 floats: [|calories_delta|, |protein_delta|, |carbs_delta|, |fat_delta|]
    """
    # Compute absolute difference for each macro nutrient
    # This penalizes both eating too much and too little
    calories_delta = abs(meal.get('calories', 0) - remaining.get('calories', 0))
    protein_delta = abs(meal.get('protein_g', 0) - remaining.get('protein_g', 0))
    carbs_delta = abs(meal.get('carbs_g', 0) - remaining.get('carbs_g', 0))
    fat_delta = abs(meal.get('fat_g', 0) - remaining.get('fat_g', 0))
    
    return [
        float(calories_delta),
        float(protein_delta),
        float(carbs_delta),
        float(fat_delta)
    ]


def compute_cuisine_match(meal: Dict[str, Any], user_preference: str) -> int:
    """
    Compute cuisine match feature: 1 if meal cuisine matches user preference, else 0.
    
    Rationale:
    - Users are more likely to enjoy and accept meals from their preferred cuisine
    - This is a simple binary preference signal
    - If user has no preference (None), all meals get 0 (no boost)
    
    Example:
    - User prefers "italian"
    - Meal A: cuisine="italian" → match = 1 (boosted)
    - Meal B: cuisine="mexican" → match = 0 (not boosted)
    - Meal C: cuisine="italian" → match = 1 (boosted)
    
    Args:
        meal: Dictionary with key: cuisine_type (e.g., "italian", "mexican")
        user_preference: User's preferred cuisine type (or None for no preference)
        
    Returns:
        1 if match, 0 if no match or no preference
    """
    # If user has no preference, return 0 (no boost)
    if user_preference is None:
        return 0
    
    # Check if meal's cuisine matches user's preference (case-insensitive)
    meal_cuisine = meal.get('cuisine_type', '').lower()
    user_pref_lower = user_preference.lower()
    
    return 1 if meal_cuisine == user_pref_lower else 0


def compute_meal_slot_match(meal: Dict[str, Any], requested_slot: str) -> int:
    """
    Compute meal slot match feature: 1 if meal fits requested slot, else 0.
    
    Rationale:
    - Meals are categorized as breakfast, lunch, dinner, or snack
    - Users request meals for specific slots (e.g., "I need breakfast")
    - Matching the slot ensures appropriate meals (no dinner for breakfast)
    - This is a HARD constraint feature - mismatches should be heavily penalized
    
    Example:
    - User requests "breakfast"
    - Meal A: meal_slot="breakfast" → match = 1 (appropriate)
    - Meal B: meal_slot="dinner" → match = 0 (inappropriate, too heavy)
    - Meal C: meal_slot="snack" → match = 0 (inappropriate, too light)
    
    Args:
        meal: Dictionary with key: meal_slot (e.g., "breakfast", "lunch", "dinner", "snack")
        requested_slot: The meal slot being requested by the user
        
    Returns:
        1 if match, 0 if no match
    """
    # Check if meal's slot matches the requested slot (case-insensitive)
    meal_slot = meal.get('meal_slot', '').lower()
    requested_slot_lower = requested_slot.lower()
    
    return 1 if meal_slot == requested_slot_lower else 0


def compute_days_since_last_eaten(meal: Dict[str, Any], user_history: list) -> int:
    """
    Compute days since user last ate this meal (recency feature).
    
    Rationale:
    - Users want VARIETY in their meal recommendations
    - Recently eaten meals should be deprioritized (avoid repetition)
    - Never-eaten meals should be boosted (encourage exploration)
    - Use 999 as default for never-eaten to strongly boost new meals
    
    Example:
    - Today is Day 100
    - Meal A: last eaten Day 98 → recency = 2 days (very recent, penalize)
    - Meal B: last eaten Day 85 → recency = 15 days (moderate, neutral)
    - Meal C: never eaten → recency = 999 days (boost exploration)
    
    Args:
        meal: Dictionary with key: id (meal identifier)
        user_history: List of dicts with keys: meal_id, days_ago
                     Example: [{'meal_id': 'meal_123', 'days_ago': 5}, ...]
        
    Returns:
        Days since last eaten (999 if never eaten)
    """
    meal_id = meal.get('id', '')
    
    # Search through user's meal history for this meal
    for history_entry in user_history:
        if history_entry.get('meal_id', '') == meal_id:
            return int(history_entry.get('days_ago', 999))
    
    # If meal not found in history, return 999 (never eaten)
    # This encourages variety and exploration of new meals
    return 999


def engineer_features(
    user: Dict[str, Any],
    meal: Dict[str, Any],
    remaining: Dict[str, float],
    history: list
) -> list:
    """
    Engineer complete 7-feature vector for a (user, meal) pair.
    
    This is the MAIN feature engineering function that combines all individual
    features into the final input vector for the LightGBM model.
    
    Feature Vector (7 elements in this exact order):
    1. macro_delta_calories: |meal.calories - remaining.calories|
    2. macro_delta_protein: |meal.protein_g - remaining.protein_g|
    3. macro_delta_carbs: |meal.carbs_g - remaining.carbs_g|
    4. macro_delta_fat: |meal.fat_g - remaining.fat_g|
    5. cuisine_match: 1 if meal.cuisine matches user.cuisine_preference else 0
    6. meal_slot_match: 1 if meal.meal_slot matches user.requested_slot else 0
    7. days_since_last_eaten: days since user ate this meal (999 if never)
    
    Feature Rationale:
    - Features 1-4 (macro deltas): Capture nutritional fit quality
    - Feature 5 (cuisine): Captures user taste preference
    - Feature 6 (meal slot): Ensures meal appropriateness for time of day
    - Feature 7 (recency): Encourages variety and exploration
    
    Example:
    User wants breakfast, prefers Italian, has 400 cal/30g protein/40g carbs/15g fat remaining
    
    Meal A: Italian breakfast, 380 cal/28g protein/38g carbs/14g fat, eaten 5 days ago
    → [20, 2, 2, 1, 1, 1, 5] (excellent fit - all features align)
    
    Meal B: Mexican dinner, 700 cal/50g protein/60g carbs/25g fat, never eaten
    → [300, 20, 20, 10, 0, 0, 999] (poor fit - wrong slot, too much food)
    
    Args:
        user: Dictionary with keys: cuisine_preference, requested_slot
        meal: Dictionary with keys: id, calories, protein_g, carbs_g, fat_g, 
              cuisine_type, meal_slot
        remaining: Dictionary with keys: calories, protein_g, carbs_g, fat_g
        history: List of user's meal history (for recency calculation)
        
    Returns:
        List of 7 floats representing the complete feature vector
    """
    # Feature 1-4: Macro delta features (nutritional fit)
    macro_deltas = compute_macro_delta(meal, remaining)
    
    # Feature 5: Cuisine match (taste preference)
    cuisine_match = compute_cuisine_match(meal, user.get('cuisine_preference'))
    
    # Feature 6: Meal slot match (appropriateness for time of day)
    meal_slot_match = compute_meal_slot_match(meal, user.get('requested_slot', ''))
    
    # Feature 7: Recency (variety and exploration)
    days_since = compute_days_since_last_eaten(meal, history)
    
    # Combine all features into final 7-element vector
    # ORDER MATTERS - this must match the training schema
    feature_vector = [
        macro_deltas[0],  # calories_delta
        macro_deltas[1],  # protein_delta
        macro_deltas[2],  # carbs_delta
        macro_deltas[3],  # fat_delta
        float(cuisine_match),
        float(meal_slot_match),
        float(days_since)
    ]
    
    return feature_vector


# =============================================================================
# Production Data Loading Functions (for Incremental Retraining)
# =============================================================================

def load_production_events(supabase_url: str, supabase_key: str) -> pd.DataFrame:
    """
    Load meal recommendation events from the production database.
    
    Queries the meal_recommendation_events table in Supabase to retrieve
    logged user interactions with meal recommendations. This data is used
    for incremental model retraining.
    
    Args:
        supabase_url: Supabase project URL
        supabase_key: Supabase service role key (for database access)
        
    Returns:
        DataFrame with columns:
        - id: Event UUID
        - user_id: User identifier
        - recommended_meal_ids: Array of meal IDs shown to user
        - requested_meal_slot: Meal slot requested (breakfast/lunch/dinner/snack)
        - user_profile_snapshot: JSON snapshot of user profile at recommendation time
        - remaining_macros_snapshot: JSON snapshot of remaining macros
        - timestamp: When recommendation was made
        - outcome: User response ('accepted', 'rejected_logged_other', NULL)
        - accepted_meal_id: ID of accepted meal (if outcome='accepted')
    """
    print("\n" + "="*80)
    print("Loading Production Events from Supabase")
    print("="*80)
    
    try:
        from supabase import create_client, Client
    except ImportError:
        print("ERROR: supabase-py library not installed")
        print("Install with: pip install supabase")
        sys.exit(1)
    
    # Initialize Supabase client
    print(f"Connecting to Supabase: {supabase_url}")
    supabase: Client = create_client(supabase_url, supabase_key)
    
    # Query meal_recommendation_events table
    # We'll fetch all events (can add date filters later if needed)
    try:
        response = supabase.table('meal_recommendation_events').select('*').execute()
        events_data = response.data
        
        if not events_data:
            print("⚠️  No production events found in database")
            return pd.DataFrame()
        
        # Convert to DataFrame
        events_df = pd.DataFrame(events_data)
        
        print(f"✓ Loaded {len(events_df)} production events")
        print(f"  Events with outcome='accepted': {len(events_df[events_df['outcome'] == 'accepted'])}")
        print(f"  Events with outcome='rejected_logged_other': {len(events_df[events_df['outcome'] == 'rejected_logged_other'])}")
        print(f"  Events with outcome=NULL: {len(events_df[events_df['outcome'].isna()])}")
        
        return events_df
        
    except Exception as e:
        print(f"ERROR: Failed to query meal_recommendation_events: {e}")
        sys.exit(1)


def convert_events_to_pairs(
    events_df: pd.DataFrame,
    meals_df: pd.DataFrame
) -> Tuple[List[List[float]], List[float]]:
    """
    Convert logged recommendation events to (user, meal) training pairs.
    
    Creates training examples from production logs:
    - Accepted meals (outcome='accepted') → label = 5.0 (strong positive signal)
    - Rejected meals (outcome='rejected_logged_other' or NULL) → label = 1.0 (negative signal)
    - Recommended but not accepted → label = 2.0 (weak negative signal)
    
    For each event, creates one training pair per recommended meal with appropriate labels.
    
    Args:
        events_df: DataFrame with production events from load_production_events()
        meals_df: DataFrame with meal data (needed to look up meal nutritional info)
        
    Returns:
        Tuple of (X, y):
        - X: List of feature vectors (each is a list of 7 floats)
        - y: List of labels (outcome-based ratings)
    """
    print("\n" + "="*80)
    print("Converting Production Events to Training Pairs")
    print("="*80)
    
    if events_df.empty:
        print("No events to convert")
        return [], []
    
    X = []  # Feature vectors
    y = []  # Labels
    
    # Create meal lookup dictionary for fast access
    meals_dict = {}
    for _, meal_row in meals_df.iterrows():
        meals_dict[str(meal_row['id'])] = {
            'id': str(meal_row['id']),
            'calories': meal_row.get('calories', 0),
            'protein_g': meal_row.get('protein_g', 0),
            'carbs_g': meal_row.get('carbs_g', 0),
            'fat_g': meal_row.get('total_fat_g', meal_row.get('fat_g', 0)),
            'cuisine_type': meal_row.get('cuisine_type', ''),
            'meal_slot': meal_row.get('meal_slot', '')
        }
    
    # Process each event
    for _, event in events_df.iterrows():
        # Parse JSON snapshots
        try:
            user_profile = json.loads(event['user_profile_snapshot']) if isinstance(event['user_profile_snapshot'], str) else event['user_profile_snapshot']
            remaining_macros = json.loads(event['remaining_macros_snapshot']) if isinstance(event['remaining_macros_snapshot'], str) else event['remaining_macros_snapshot']
        except (json.JSONDecodeError, TypeError) as e:
            print(f"⚠️  Skipping event {event.get('id', 'unknown')}: Failed to parse JSON snapshots: {e}")
            continue
        
        # Get recommended meals and outcome
        recommended_meal_ids = event['recommended_meal_ids']
        if not recommended_meal_ids:
            continue
        
        outcome = event.get('outcome')
        accepted_meal_id = event.get('accepted_meal_id')
        requested_slot = event.get('requested_meal_slot', '')
        
        # Extract user context
        cuisine_pref = user_profile.get('cuisine_preference')
        
        # Create user context dict
        user_context = {
            'cuisine_preference': cuisine_pref,
            'requested_slot': requested_slot
        }
        
        # Convert remaining macros to expected format
        remaining = {
            'calories': float(remaining_macros.get('calories', 0)),
            'protein_g': float(remaining_macros.get('protein_g', 0)),
            'carbs_g': float(remaining_macros.get('carbs_g', 0)),
            'fat_g': float(remaining_macros.get('fat_g', 0))
        }
        
        # Simulate empty user history (we don't have this data in events)
        # In a more sophisticated version, we could query meal_logs to build history
        user_history = []
        
        # Process each recommended meal
        for meal_id in recommended_meal_ids:
            meal_id_str = str(meal_id)
            
            # Look up meal data
            if meal_id_str not in meals_dict:
                print(f"⚠️  Meal {meal_id_str} not found in meals table, skipping")
                continue
            
            meal = meals_dict[meal_id_str]
            
            # Engineer features
            features = engineer_features(user_context, meal, remaining, user_history)
            
            # Determine label based on outcome
            if outcome == 'accepted' and meal_id_str == str(accepted_meal_id):
                # User accepted this meal → strong positive signal
                label = 5.0
            elif outcome == 'accepted' and meal_id_str != str(accepted_meal_id):
                # User accepted a different meal → weak negative for this one
                label = 2.0
            elif outcome == 'rejected_logged_other':
                # User rejected recommendations and logged something else → negative signal
                label = 1.0
            else:  # outcome is NULL (implicit rejection)
                # User dismissed recommendations → weak negative signal
                label = 1.5
            
            X.append(features)
            y.append(label)
    
    print(f"✓ Generated {len(X)} training pairs from production events")
    if y:
        print(f"  Label distribution: min={min(y):.2f}, max={max(y):.2f}, mean={np.mean(y):.2f}")
    
    return X, y


def combine_datasets(
    food_X: List[List[float]],
    food_y: List[float],
    production_X: List[List[float]],
    production_y: List[float],
    production_weight: float = 2.0
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Combine Food.com dataset with production feedback data.
    
    Merges the synthetic training data from Food.com with real user feedback
    from production. Production data is weighted higher (by default 2x) to
    prioritize learning from actual user behavior.
    
    Weighting Strategy:
    - Duplicate production examples N times (where N = production_weight)
    - This effectively increases their influence during training
    - Higher weight means model learns more from real user feedback
    
    Args:
        food_X: Feature vectors from Food.com dataset
        food_y: Labels from Food.com dataset
        production_X: Feature vectors from production events
        production_y: Labels from production events
        production_weight: Multiplicative weight for production data (default: 2.0)
        
    Returns:
        Tuple of (X_combined, y_combined) as numpy arrays ready for training
    """
    print("\n" + "="*80)
    print("Combining Food.com and Production Datasets")
    print("="*80)
    
    print(f"Food.com dataset: {len(food_X):,} samples")
    print(f"Production dataset: {len(production_X):,} samples")
    print(f"Production weight: {production_weight}x")
    
    # Convert to lists if needed
    all_X = list(food_X)
    all_y = list(food_y)
    
    # Add production data with weighting (duplicate production samples)
    if production_X and production_y:
        # Calculate number of duplicates (round to nearest integer)
        n_duplicates = max(1, int(round(production_weight)))
        
        print(f"Duplicating production samples {n_duplicates}x for weighting")
        
        for _ in range(n_duplicates):
            all_X.extend(production_X)
            all_y.extend(production_y)
        
        print(f"✓ Combined dataset: {len(all_X):,} samples")
        print(f"  Effective production proportion: {len(production_X) * n_duplicates / len(all_X) * 100:.1f}%")
    else:
        print("⚠️  No production data to combine, using Food.com data only")
    
    # Convert to numpy arrays
    X_combined = np.array(all_X, dtype=np.float32)
    y_combined = np.array(all_y, dtype=np.float32)
    
    return X_combined, y_combined


# =============================================================================
# Training Pipeline Functions
# =============================================================================

def create_training_pairs(
    recipes_df: pd.DataFrame,
    synthetic_users: pd.DataFrame,
    contexts_per_user: int = 10
) -> Tuple[List[List[float]], List[float]]:
    """
    Create (user, meal) training pairs with engineered features and ratings as labels.
    
    For each synthetic user, creates multiple contexts (different remaining macros and
    meal slot requests), then pairs each context with all recipes to create training examples.
    
    Args:
        recipes_df: DataFrame with cleaned recipe data including nutritional info and ratings
        synthetic_users: DataFrame with simulated user profiles
        contexts_per_user: Number of different contexts to generate per user
        
    Returns:
        Tuple of (X, y):
        - X: List of feature vectors (each is a list of 7 floats)
        - y: List of rating labels (continuous values from recipe ratings)
    """
    print("\n" + "="*80)
    print("Creating Training Pairs")
    print("="*80)
    
    X = []  # Feature vectors
    y = []  # Labels (ratings)
    
    total_users = len(synthetic_users)
    total_recipes = len(recipes_df)
    
    print(f"Synthetic users: {total_users}")
    print(f"Recipes: {total_recipes}")
    print(f"Contexts per user: {contexts_per_user}")
    print(f"Expected pairs: ~{total_users * contexts_per_user * total_recipes:,}")
    
    # Process users in batches for progress reporting
    for user_idx, user_row in synthetic_users.iterrows():
        if user_idx % 1000 == 0 and user_idx > 0:
            print(f"  Processed {user_idx}/{total_users} users... ({len(X):,} pairs generated)")
        
        # Convert user row to dict
        user_profile = user_row.to_dict()
        
        # Compute user's TDEE and macro targets
        tdee = compute_tdee(user_profile)
        targets = compute_macro_targets(user_profile, tdee)
        
        # Generate multiple contexts for this user (different times of day, meal slots)
        for context_idx in range(contexts_per_user):
            # Simulate remaining macros for this context
            remaining = simulate_remaining_macros(targets)
            
            # Simulate cuisine preference
            cuisine_pref = simulate_cuisine_preference()
            
            # Simulate meal slot request
            requested_slot = simulate_meal_slot_request()
            
            # Simulate user history (for recency feature)
            # For training, we'll simulate some meals as previously eaten
            user_history = []
            if random.random() < 0.3:  # 30% chance of having history
                # Randomly select 1-5 recipes as "previously eaten"
                num_history_items = random.randint(1, 5)
                sampled_recipes = recipes_df.sample(n=min(num_history_items, len(recipes_df)))
                for _, hist_recipe in sampled_recipes.iterrows():
                    days_ago = random.randint(1, 60)  # 1-60 days ago
                    user_history.append({
                        'meal_id': str(hist_recipe['id']),
                        'days_ago': days_ago
                    })
            
            # Create user context dict for feature engineering
            user_context = {
                'cuisine_preference': cuisine_pref,
                'requested_slot': requested_slot
            }
            
            # Pair this context with all recipes
            for _, recipe_row in recipes_df.iterrows():
                # Convert recipe to dict format for feature engineering
                recipe_dict = {
                    'id': str(recipe_row['id']),
                    'calories': recipe_row['calories'],
                    'protein_g': recipe_row['protein_g'],
                    'carbs_g': recipe_row['carbs_g'],
                    'fat_g': recipe_row['total_fat_g'],  # Note: using total_fat_g from data_prep
                    'cuisine_type': recipe_row['cuisine_type'],
                    'meal_slot': recipe_row['meal_slot']
                }
                
                # Engineer features for this (user, meal) pair
                features = engineer_features(user_context, recipe_dict, remaining, user_history)
                
                # Use recipe rating as the label
                # Ratings in Food.com are typically 1-5 stars
                # We need to handle the 'rating' column from interactions data
                # For now, we'll use a synthetic rating based on fit quality
                # In a real scenario, we'd join with interactions data
                
                # Compute a synthetic rating based on feature quality
                # This is a placeholder - ideally we'd use actual user ratings from interactions
                rating = compute_synthetic_rating(features)
                
                X.append(features)
                y.append(rating)
    
    print(f"\n✓ Generated {len(X):,} training pairs")
    print(f"  Feature vector size: {len(X[0])} features")
    print(f"  Label distribution: min={min(y):.2f}, max={max(y):.2f}, mean={np.mean(y):.2f}")
    
    return X, y


def compute_synthetic_rating(features: List[float]) -> float:
    """
    Compute a synthetic rating based on feature quality.
    
    This is a placeholder for actual user ratings. In production, we'd use
    real ratings from the interactions dataset. For training purposes, we
    create synthetic ratings based on how well the meal "fits" the user context.
    
    Rating logic:
    - Start at 3.0 (neutral rating)
    - Penalize large macro deltas (poor nutritional fit)
    - Boost for cuisine match (+0.5)
    - Boost for meal slot match (+1.0, critical)
    - Slight boost for recency (variety)
    
    Args:
        features: 7-element feature vector
        
    Returns:
        Synthetic rating (1.0 to 5.0)
    """
    base_rating = 3.0
    
    # Extract features
    cal_delta = features[0]
    protein_delta = features[1]
    carbs_delta = features[2]
    fat_delta = features[3]
    cuisine_match = features[4]
    slot_match = features[5]
    days_since = features[6]
    
    # Penalize large macro deltas (poor fit)
    # Normalize deltas to 0-1 range and penalize
    cal_penalty = min(cal_delta / 500, 1.0) * -1.5  # Up to -1.5 stars
    protein_penalty = min(protein_delta / 50, 1.0) * -0.5  # Up to -0.5 stars
    carbs_penalty = min(carbs_delta / 50, 1.0) * -0.3  # Up to -0.3 stars
    fat_penalty = min(fat_delta / 30, 1.0) * -0.3  # Up to -0.3 stars
    
    # Boost for matches
    cuisine_boost = 0.5 if cuisine_match == 1 else 0
    slot_boost = 1.0 if slot_match == 1 else -1.0  # Critical feature
    
    # Slight boost for variety (newer meals)
    recency_boost = 0.2 if days_since > 14 else 0
    
    # Compute final rating
    rating = base_rating + cal_penalty + protein_penalty + carbs_penalty + fat_penalty
    rating += cuisine_boost + slot_boost + recency_boost
    
    # Clamp to 1.0-5.0 range
    rating = max(1.0, min(5.0, rating))
    
    # Add some noise to make it more realistic
    rating += np.random.normal(0, 0.2)
    rating = max(1.0, min(5.0, rating))
    
    return rating


def evaluate_model(
    model: lgb.LGBMRegressor,
    X_test: np.ndarray,
    y_test: np.ndarray
) -> Dict[str, float]:
    """
    Evaluate the trained model on test set.
    
    Computes three key metrics:
    1. NDCG@5: Normalized Discounted Cumulative Gain at rank 5
       - Measures ranking quality for top-5 recommendations
       - Range: 0.0 (worst) to 1.0 (perfect)
       - Target: >= 0.3
    
    2. Precision@5: Fraction of top-5 that are high-quality (rating >= 4.0)
       - Measures what % of recommendations are actually good
       - Range: 0.0 to 1.0
       - Target: >= 0.6
    
    3. MAE: Mean Absolute Error for rating prediction
       - Measures prediction accuracy
       - Lower is better
    
    Args:
        model: Trained LGBMRegressor
        X_test: Test feature vectors
        y_test: Test labels (ratings)
        
    Returns:
        Dictionary with metrics: ndcg_5, precision_5, mae
    """
    print("\n" + "="*80)
    print("Evaluating Model on Test Set")
    print("="*80)
    
    # Predict scores on test set
    y_pred = model.predict(X_test)
    
    # Compute MAE
    mae = mean_absolute_error(y_test, y_pred)
    print(f"\nMean Absolute Error: {mae:.4f}")
    
    # Compute NDCG@5
    # NDCG requires multiple queries (user contexts), so we'll compute it in groups
    # We'll treat each 100 consecutive samples as one "query" for simplicity
    group_size = 100
    n_groups = len(y_test) // group_size
    
    ndcg_scores = []
    precision_scores = []
    
    for i in range(n_groups):
        start_idx = i * group_size
        end_idx = start_idx + group_size
        
        y_true_group = y_test[start_idx:end_idx]
        y_pred_group = y_pred[start_idx:end_idx]
        
        # Compute NDCG@5 for this group
        # Reshape for sklearn's ndcg_score (expects 2D array)
        try:
            ndcg = ndcg_score([y_true_group], [y_pred_group], k=5)
            ndcg_scores.append(ndcg)
        except:
            # Skip if NDCG computation fails for this group
            pass
        
        # Compute Precision@5 for this group
        # Get top-5 indices by predicted score
        top5_indices = np.argsort(y_pred_group)[-5:]
        top5_true_ratings = y_true_group[top5_indices]
        
        # Count how many are high-quality (rating >= 4.0)
        high_quality_count = np.sum(top5_true_ratings >= 4.0)
        precision = high_quality_count / 5.0
        precision_scores.append(precision)
    
    # Average across all groups
    avg_ndcg_5 = np.mean(ndcg_scores) if ndcg_scores else 0.0
    avg_precision_5 = np.mean(precision_scores)
    
    print(f"NDCG@5: {avg_ndcg_5:.4f}")
    print(f"Precision@5: {avg_precision_5:.4f}")
    
    # Check baseline threshold
    if avg_ndcg_5 < 0.3:
        print(f"\n⚠️  WARNING: NDCG@5 ({avg_ndcg_5:.4f}) is below baseline threshold (0.3)")
    else:
        print(f"\n✓ NDCG@5 meets baseline threshold (>= 0.3)")
    
    return {
        'ndcg_5': avg_ndcg_5,
        'precision_5': avg_precision_5,
        'mae': mae
    }


def save_model_and_metadata(
    model: lgb.LGBMRegressor,
    metrics: Dict[str, float],
    feature_names: List[str],
    output_dir: str = '.',
    use_timestamp: bool = False
):
    """
    Save trained model, feature schema, and training metrics to disk.
    
    Saves three files:
    1. meal_ranker.txt (or meal_ranker_{timestamp}.txt): Serialized LightGBM model
    2. feature_schema.json: Feature metadata for validation
    3. training_metrics.json: Performance baseline metrics
    
    Args:
        model: Trained LGBMRegressor
        metrics: Dictionary with evaluation metrics
        feature_names: List of feature names in order
        output_dir: Directory to save files (default: current directory)
        use_timestamp: If True, append timestamp to model filename
    """
    print("\n" + "="*80)
    print("Saving Model and Metadata")
    print("="*80)
    
    # Use absolute path
    output_dir = os.path.abspath(output_dir)
    
    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)
    
    # Determine model filename
    if use_timestamp:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        model_filename = f'meal_ranker_{timestamp}.txt'
    else:
        model_filename = 'meal_ranker.txt'
    
    # Save model to text format
    model_path = os.path.join(output_dir, model_filename)
    model.booster_.save_model(model_path)
    print(f"\n✓ Model saved to: {model_path}")
    
    # Save feature schema
    feature_schema = {
        'version': '1.0.0',
        'feature_count': len(feature_names),
        'feature_names': feature_names,
        'feature_types': ['float'] * len(feature_names),
        'feature_descriptions': [
            'Absolute difference between meal calories and remaining calories',
            'Absolute difference between meal protein and remaining protein',
            'Absolute difference between meal carbs and remaining carbs',
            'Absolute difference between meal fat and remaining fat',
            'Binary: 1 if meal cuisine matches user preference, 0 otherwise',
            'Binary: 1 if meal slot matches requested slot, 0 otherwise',
            'Days since user last ate this meal (999 if never)'
        ]
    }
    
    schema_path = os.path.join(output_dir, 'feature_schema.json')
    with open(schema_path, 'w') as f:
        json.dump(feature_schema, f, indent=2)
    print(f"✓ Feature schema saved to: {schema_path}")
    
    # Save training metrics
    metrics_data = {
        'version': '1.0.0',
        'training_date': pd.Timestamp.now().isoformat(),
        'model_filename': model_filename,
        'metrics': metrics,
        'baseline_thresholds': {
            'ndcg_5': 0.3,
            'precision_5': 0.6
        },
        'model_config': {
            'n_estimators': model.n_estimators,
            'learning_rate': model.learning_rate,
            'max_depth': model.max_depth,
            'num_leaves': model.num_leaves
        }
    }
    
    metrics_path = os.path.join(output_dir, 'training_metrics.json')
    with open(metrics_path, 'w') as f:
        json.dump(metrics_data, f, indent=2)
    print(f"✓ Training metrics saved to: {metrics_path}")
    
    return model_filename


# =============================================================================
# Main Training Pipeline
# =============================================================================

def main_training_pipeline(use_production_logs: bool = False):
    """
    Main training pipeline that orchestrates the complete workflow.
    
    Steps:
    1. Load cleaned recipe data from data_prep.py
    2. Generate synthetic user profiles (if not using production logs only)
    3. Create training pairs with feature engineering
    4. (Optional) Load and convert production events to training pairs
    5. (Optional) Combine datasets with production data weighted higher
    6. Split into train/test sets
    7. Train LGBMRegressor model
    8. Evaluate model performance
    9. Save model and metadata
    
    Args:
        use_production_logs: If True, load production data and combine with Food.com dataset
    """
    print("="*80)
    print("LightGBM Meal Ranker Training Pipeline")
    if use_production_logs:
        print("Mode: INCREMENTAL RETRAINING (Food.com + Production Data)")
    else:
        print("Mode: INITIAL TRAINING (Food.com Only)")
    print("="*80)
    
    # Step 1: Load cleaned recipe data
    print("\n[Step 1/7] Loading cleaned recipe data...")
    recipes_path = './data/RAW_recipes_cleaned.csv'
    
    if not os.path.exists(recipes_path):
        print(f"ERROR: Cleaned recipes file not found at {recipes_path}")
        print("Please run data_prep.py first to prepare the dataset.")
        sys.exit(1)
    
    recipes_df = pd.read_csv(recipes_path)
    print(f"✓ Loaded {len(recipes_df)} recipes")
    
    # Step 2: Generate synthetic user profiles and training pairs
    print("\n[Step 2/7] Generating synthetic user profiles...")
    n_users = 1000  # Start with 1000 users for reasonable training time
    synthetic_users = simulate_user_profiles(n=n_users)
    print(f"✓ Generated {len(synthetic_users)} synthetic users")
    
    # Step 3: Create training pairs from Food.com data
    print("\n[Step 3/7] Creating training pairs from Food.com dataset...")
    contexts_per_user = 5  # 5 different contexts per user
    food_X, food_y = create_training_pairs(recipes_df, synthetic_users, contexts_per_user)
    
    # Step 4: Load production data if requested
    production_X = []
    production_y = []
    
    if use_production_logs:
        print("\n[Step 4/7] Loading production events...")
        
        # Load environment variables for Supabase credentials
        supabase_url = os.getenv('SUPABASE_URL') or os.getenv('NEXT_PUBLIC_SUPABASE_URL')
        supabase_key = os.getenv('SUPABASE_SERVICE_KEY') or os.getenv('NEXT_PUBLIC_SUPABASE_ANON_KEY')
        
        if not supabase_url or not supabase_key:
            print("ERROR: SUPABASE_URL and SUPABASE_SERVICE_KEY environment variables required")
            print("Please set these in your environment or .env file")
            sys.exit(1)
        
        # Load production events from Supabase
        events_df = load_production_events(supabase_url, supabase_key)
        
        if not events_df.empty:
            # Convert events to training pairs
            print("\n[Step 4b/7] Converting production events to training pairs...")
            production_X, production_y = convert_events_to_pairs(events_df, recipes_df)
        else:
            print("⚠️  No production events found, continuing with Food.com data only")
    else:
        print("\n[Step 4/7] Skipping production logs (not requested)")
    
    # Step 5: Combine datasets
    print("\n[Step 5/7] Preparing final training dataset...")
    
    if production_X and production_y:
        # Combine Food.com and production data with production weighted 2x
        X, y = combine_datasets(food_X, food_y, production_X, production_y, production_weight=2.0)
        use_timestamp = True  # Use timestamped filename for retrained models
    else:
        # Use Food.com data only
        X = np.array(food_X, dtype=np.float32)
        y = np.array(food_y, dtype=np.float32)
        use_timestamp = False  # Use standard filename for initial training
    
    print(f"\n✓ Final training data shape: X={X.shape}, y={y.shape}")
    
    # Step 6: Train/test split
    print("\n[Step 6/7] Splitting into train/test sets...")
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.1, random_state=42
    )
    print(f"✓ Train set: {len(X_train):,} samples")
    print(f"✓ Test set: {len(X_test):,} samples")
    
    # Step 7: Train LGBMRegressor
    print("\n[Step 7/7] Training LGBMRegressor...")
    print("Hyperparameters:")
    print("  n_estimators: 100")
    print("  learning_rate: 0.1")
    print("  max_depth: 5")
    print("  num_leaves: 31")
    
    model = lgb.LGBMRegressor(
        n_estimators=100,
        learning_rate=0.1,
        max_depth=5,
        num_leaves=31,
        random_state=42,
        verbose=-1  # Suppress training output
    )
    
    model.fit(X_train, y_train)
    print("✓ Model training complete")
    
    # Step 8: Evaluate model
    print("\n[Step 8/7] Evaluating model...")
    metrics = evaluate_model(model, X_test, y_test)
    
    # Assert NDCG@5 threshold
    if metrics['ndcg_5'] < 0.3:
        error_msg = f"Model quality check FAILED: NDCG@5 ({metrics['ndcg_5']:.4f}) is below threshold (0.3)"
        print(f"\n❌ {error_msg}")
        raise ValueError(error_msg)
    
    # Step 9: Save model and metadata
    print("\n[Step 9/7] Saving model and metadata...")
    feature_names = [
        'macro_delta_calories',
        'macro_delta_protein',
        'macro_delta_carbs',
        'macro_delta_fat',
        'cuisine_match',
        'meal_slot_match',
        'days_since_last_eaten'
    ]
    
    model_filename = save_model_and_metadata(
        model, 
        metrics, 
        feature_names,
        use_timestamp=use_timestamp
    )
    
    print("\n" + "="*80)
    print("Training Pipeline Complete!")
    print("="*80)
    print(f"\n📊 Final Metrics:")
    print(f"  NDCG@5: {metrics['ndcg_5']:.4f}")
    print(f"  Precision@5: {metrics['precision_5']:.4f}")
    print(f"  MAE: {metrics['mae']:.4f}")
    print(f"\n✓ Model ready for deployment: lib/meal-recommender/{model_filename}")


if __name__ == '__main__':
    # Parse command-line arguments
    parser = argparse.ArgumentParser(
        description='Train LightGBM Meal Ranker model',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Train on Food.com dataset only (initial training)
  python train.py
  
  # Train on Food.com + production feedback (incremental retraining)
  python train.py --use-production-logs
  
Environment Variables (required for --use-production-logs):
  SUPABASE_URL or NEXT_PUBLIC_SUPABASE_URL: Supabase project URL
  SUPABASE_SERVICE_KEY or NEXT_PUBLIC_SUPABASE_ANON_KEY: Supabase API key
        """
    )
    
    parser.add_argument(
        '--use-production-logs',
        action='store_true',
        help='Load production recommendation events and combine with Food.com dataset for incremental retraining'
    )
    
    args = parser.parse_args()
    
    # Load environment variables from .env.local if it exists
    env_path = Path(__file__).parent.parent.parent / '.env.local'
    if env_path.exists():
        print(f"Loading environment variables from {env_path}")
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    os.environ[key] = value
    
    # Run the main training pipeline
    main_training_pipeline(use_production_logs=args.use_production_logs)
