-- Seed data for meals table
-- Contains 100+ diverse meals across breakfast, lunch, dinner, and snack categories
-- Covers American, Italian, Mexican, Asian, and Mediterranean cuisines

-- BREAKFAST MEALS (25 meals)
INSERT INTO meals (id, name, description, cuisine_type, meal_slot, calories, protein_g, carbs_g, fat_g, ingredients) VALUES
('breakfast_001', 'Classic Oatmeal with Berries', 'Steel-cut oats topped with fresh berries and honey', 'American', 'breakfast', 320, 12.5, 58.0, 6.5, ARRAY['oats', 'blueberries', 'strawberries', 'honey', 'almonds']),
('breakfast_002', 'Greek Yogurt Parfait', 'Greek yogurt layered with granola and mixed berries', 'Mediterranean', 'breakfast', 280, 18.0, 42.0, 7.0, ARRAY['greek yogurt', 'granola', 'berries', 'honey']),
('breakfast_003', 'Avocado Toast with Eggs', 'Whole grain toast with smashed avocado and poached eggs', 'American', 'breakfast', 420, 22.0, 38.0, 22.0, ARRAY['whole grain bread', 'avocado', 'eggs', 'tomatoes', 'olive oil']),
('breakfast_004', 'Breakfast Burrito', 'Scrambled eggs, black beans, cheese, and salsa in a tortilla', 'Mexican', 'breakfast', 480, 26.0, 48.0, 20.0, ARRAY['eggs', 'black beans', 'tortilla', 'cheese', 'salsa', 'peppers']),
('breakfast_005', 'Banana Protein Pancakes', 'Fluffy pancakes made with banana and protein powder', 'American', 'breakfast', 380, 28.0, 52.0, 8.0, ARRAY['banana', 'protein powder', 'oats', 'eggs', 'maple syrup']),
('breakfast_006', 'Italian Frittata', 'Baked egg dish with vegetables and parmesan cheese', 'Italian', 'breakfast', 290, 24.0, 12.0, 18.0, ARRAY['eggs', 'spinach', 'tomatoes', 'onions', 'parmesan cheese']),
('breakfast_007', 'Smoothie Bowl', 'Thick fruit smoothie topped with granola and seeds', 'American', 'breakfast', 340, 14.0, 58.0, 9.0, ARRAY['banana', 'berries', 'protein powder', 'granola', 'chia seeds']),
('breakfast_008', 'Congee with Chicken', 'Rice porridge with shredded chicken and ginger', 'Asian', 'breakfast', 310, 22.0, 42.0, 6.0, ARRAY['rice', 'chicken', 'ginger', 'green onions', 'soy sauce']),
('breakfast_009', 'Shakshuka', 'Poached eggs in spiced tomato sauce', 'Mediterranean', 'breakfast', 320, 18.0, 24.0, 16.0, ARRAY['eggs', 'tomatoes', 'bell peppers', 'onions', 'cumin', 'paprika']),
('breakfast_010', 'Breakfast Quesadilla', 'Cheese and egg quesadilla with salsa', 'Mexican', 'breakfast', 450, 24.0, 42.0, 22.0, ARRAY['tortilla', 'eggs', 'cheese', 'salsa', 'avocado']),
('breakfast_011', 'Chia Pudding', 'Overnight chia seeds in almond milk with fruit', 'American', 'breakfast', 260, 10.0, 36.0, 10.0, ARRAY['chia seeds', 'almond milk', 'banana', 'berries', 'honey']),
('breakfast_012', 'Veggie Omelet', 'Three-egg omelet with mixed vegetables', 'American', 'breakfast', 320, 26.0, 14.0, 18.0, ARRAY['eggs', 'spinach', 'mushrooms', 'tomatoes', 'cheese']),
('breakfast_013', 'Breakfast Sushi', 'Rice rolled with eggs and vegetables', 'Asian', 'breakfast', 340, 16.0, 54.0, 7.0, ARRAY['rice', 'eggs', 'cucumber', 'avocado', 'nori']),
('breakfast_014', 'Protein Waffles', 'High-protein waffles with berries', 'American', 'breakfast', 380, 32.0, 46.0, 10.0, ARRAY['protein powder', 'oats', 'eggs', 'berries', 'maple syrup']),
('breakfast_015', 'Breakfast Pizza', 'Whole wheat crust with eggs, vegetables, and cheese', 'Italian', 'breakfast', 420, 28.0, 40.0, 18.0, ARRAY['whole wheat dough', 'eggs', 'mozzarella', 'spinach', 'tomatoes']),
('breakfast_016', 'Huevos Rancheros', 'Eggs on tortillas with beans and salsa', 'Mexican', 'breakfast', 460, 26.0, 48.0, 18.0, ARRAY['eggs', 'tortillas', 'black beans', 'salsa', 'cheese', 'avocado']),
('breakfast_017', 'Miso Soup with Tofu', 'Traditional miso soup with tofu and seaweed', 'Asian', 'breakfast', 180, 12.0, 18.0, 6.0, ARRAY['miso paste', 'tofu', 'seaweed', 'green onions', 'mushrooms']),
('breakfast_018', 'French Toast', 'Whole grain bread dipped in egg mixture and grilled', 'American', 'breakfast', 400, 18.0, 56.0, 12.0, ARRAY['whole grain bread', 'eggs', 'milk', 'cinnamon', 'maple syrup']),
('breakfast_019', 'Mediterranean Breakfast Bowl', 'Quinoa with vegetables, feta, and olives', 'Mediterranean', 'breakfast', 380, 16.0, 42.0, 16.0, ARRAY['quinoa', 'cucumber', 'tomatoes', 'feta', 'olives', 'olive oil']),
('breakfast_020', 'Breakfast Tacos', 'Soft tacos with scrambled eggs and salsa', 'Mexican', 'breakfast', 440, 24.0, 44.0, 20.0, ARRAY['tortillas', 'eggs', 'cheese', 'salsa', 'beans']),
('breakfast_021', 'Bagel with Lox', 'Whole wheat bagel with cream cheese and smoked salmon', 'American', 'breakfast', 420, 26.0, 48.0, 14.0, ARRAY['whole wheat bagel', 'cream cheese', 'smoked salmon', 'capers', 'onions']),
('breakfast_022', 'Rice Paper Rolls', 'Fresh rolls with vegetables and shrimp', 'Asian', 'breakfast', 280, 18.0, 38.0, 6.0, ARRAY['rice paper', 'shrimp', 'lettuce', 'carrots', 'mint', 'peanut sauce']),
('breakfast_023', 'Egg White Scramble', 'Scrambled egg whites with vegetables', 'American', 'breakfast', 220, 28.0, 16.0, 4.0, ARRAY['egg whites', 'spinach', 'mushrooms', 'peppers', 'onions']),
('breakfast_024', 'Caprese Breakfast Plate', 'Fresh mozzarella, tomatoes, and basil with eggs', 'Italian', 'breakfast', 360, 26.0, 18.0, 22.0, ARRAY['mozzarella', 'tomatoes', 'basil', 'eggs', 'olive oil']),
('breakfast_025', 'Breakfast Grain Bowl', 'Mixed grains with vegetables and a fried egg', 'American', 'breakfast', 400, 20.0, 52.0, 14.0, ARRAY['quinoa', 'brown rice', 'vegetables', 'eggs', 'avocado'])

-- LUNCH MEALS (25 meals)
,('lunch_001', 'Grilled Chicken Salad', 'Mixed greens with grilled chicken breast and vinaigrette', 'American', 'lunch', 380, 42.0, 24.0, 14.0, ARRAY['chicken breast', 'mixed greens', 'tomatoes', 'cucumber', 'olive oil', 'vinegar']),
('lunch_002', 'Caesar Salad with Shrimp', 'Romaine lettuce with grilled shrimp and Caesar dressing', 'American', 'lunch', 420, 38.0, 28.0, 18.0, ARRAY['shrimp', 'romaine lettuce', 'parmesan', 'croutons', 'caesar dressing']),
('lunch_003', 'Margherita Pizza', 'Thin crust pizza with tomato, mozzarella, and basil', 'Italian', 'lunch', 520, 24.0, 62.0, 20.0, ARRAY['pizza dough', 'tomato sauce', 'mozzarella', 'basil', 'olive oil']),
('lunch_004', 'Chicken Burrito Bowl', 'Rice bowl with grilled chicken, beans, and vegetables', 'Mexican', 'lunch', 560, 46.0, 58.0, 18.0, ARRAY['chicken', 'rice', 'black beans', 'peppers', 'onions', 'salsa']),
('lunch_005', 'Pad Thai', 'Stir-fried rice noodles with shrimp and peanuts', 'Asian', 'lunch', 540, 32.0, 64.0, 18.0, ARRAY['rice noodles', 'shrimp', 'peanuts', 'bean sprouts', 'lime', 'fish sauce']),
('lunch_006', 'Greek Salad with Grilled Fish', 'Mediterranean salad with white fish', 'Mediterranean', 'lunch', 420, 38.0, 22.0, 20.0, ARRAY['white fish', 'cucumber', 'tomatoes', 'olives', 'feta', 'olive oil']),
('lunch_007', 'Turkey and Avocado Wrap', 'Whole wheat wrap with turkey and avocado', 'American', 'lunch', 480, 36.0, 44.0, 18.0, ARRAY['turkey', 'whole wheat tortilla', 'avocado', 'lettuce', 'tomato']),
('lunch_008', 'Penne Arrabbiata', 'Pasta with spicy tomato sauce', 'Italian', 'lunch', 480, 16.0, 74.0, 14.0, ARRAY['penne pasta', 'tomatoes', 'garlic', 'chili flakes', 'olive oil']),
('lunch_009', 'Chicken Fajita Bowl', 'Grilled chicken with peppers and onions over rice', 'Mexican', 'lunch', 520, 44.0, 54.0, 16.0, ARRAY['chicken', 'rice', 'bell peppers', 'onions', 'fajita seasoning']),
('lunch_010', 'Teriyaki Salmon Bowl', 'Glazed salmon with rice and vegetables', 'Asian', 'lunch', 580, 42.0, 56.0, 20.0, ARRAY['salmon', 'rice', 'broccoli', 'carrots', 'teriyaki sauce']),
('lunch_011', 'Quinoa Buddha Bowl', 'Quinoa with roasted vegetables and tahini', 'Mediterranean', 'lunch', 460, 18.0, 58.0, 18.0, ARRAY['quinoa', 'chickpeas', 'vegetables', 'tahini', 'lemon']),
('lunch_012', 'Tuna Salad Sandwich', 'Whole grain sandwich with tuna salad', 'American', 'lunch', 420, 32.0, 42.0, 14.0, ARRAY['tuna', 'whole grain bread', 'mayo', 'celery', 'lettuce']),
('lunch_013', 'Lasagna', 'Layered pasta with meat sauce and cheese', 'Italian', 'lunch', 620, 38.0, 56.0, 28.0, ARRAY['lasagna noodles', 'ground beef', 'tomato sauce', 'ricotta', 'mozzarella']),
('lunch_014', 'Chicken Enchiladas', 'Rolled tortillas with chicken and cheese in sauce', 'Mexican', 'lunch', 580, 42.0, 52.0, 22.0, ARRAY['tortillas', 'chicken', 'enchilada sauce', 'cheese', 'onions']),
('lunch_015', 'Bibimbap', 'Korean rice bowl with vegetables and egg', 'Asian', 'lunch', 520, 24.0, 68.0, 16.0, ARRAY['rice', 'vegetables', 'egg', 'beef', 'gochujang sauce']),
('lunch_016', 'Mediterranean Chicken Pita', 'Grilled chicken in pita with tzatziki', 'Mediterranean', 'lunch', 460, 40.0, 46.0, 14.0, ARRAY['chicken', 'pita bread', 'tzatziki', 'cucumber', 'tomatoes']),
('lunch_017', 'BBQ Chicken Sandwich', 'Grilled chicken with BBQ sauce on a bun', 'American', 'lunch', 520, 42.0, 54.0, 16.0, ARRAY['chicken breast', 'bun', 'bbq sauce', 'coleslaw', 'pickles']),
('lunch_018', 'Caprese Panini', 'Grilled sandwich with mozzarella, tomato, and basil', 'Italian', 'lunch', 440, 22.0, 48.0, 18.0, ARRAY['bread', 'mozzarella', 'tomatoes', 'basil', 'olive oil']),
('lunch_019', 'Fish Tacos', 'Grilled fish in soft tortillas with cabbage slaw', 'Mexican', 'lunch', 480, 36.0, 48.0, 16.0, ARRAY['white fish', 'tortillas', 'cabbage', 'lime', 'salsa']),
('lunch_020', 'Vietnamese Pho', 'Rice noodle soup with beef and herbs', 'Asian', 'lunch', 420, 28.0, 52.0, 10.0, ARRAY['rice noodles', 'beef', 'broth', 'herbs', 'lime']),
('lunch_021', 'Falafel Wrap', 'Chickpea falafel in wrap with tahini sauce', 'Mediterranean', 'lunch', 480, 18.0, 62.0, 18.0, ARRAY['falafel', 'pita', 'tahini', 'lettuce', 'tomatoes']),
('lunch_022', 'Cobb Salad', 'Salad with chicken, bacon, eggs, and avocado', 'American', 'lunch', 540, 44.0, 18.0, 32.0, ARRAY['chicken', 'bacon', 'eggs', 'avocado', 'lettuce', 'tomatoes']),
('lunch_023', 'Spaghetti Carbonara', 'Pasta with eggs, cheese, and pancetta', 'Italian', 'lunch', 620, 32.0, 68.0, 26.0, ARRAY['spaghetti', 'eggs', 'pancetta', 'parmesan', 'black pepper']),
('lunch_024', 'Carnitas Bowl', 'Slow-cooked pork with rice and beans', 'Mexican', 'lunch', 600, 42.0, 58.0, 22.0, ARRAY['pork', 'rice', 'beans', 'salsa', 'cilantro']),
('lunch_025', 'Sushi Bowl', 'Deconstructed sushi with rice, fish, and vegetables', 'Asian', 'lunch', 480, 32.0, 62.0, 12.0, ARRAY['rice', 'tuna', 'avocado', 'cucumber', 'soy sauce', 'sesame'])

-- DINNER MEALS (30 meals)
,('dinner_001', 'Grilled Steak with Vegetables', 'Sirloin steak with roasted vegetables', 'American', 'dinner', 580, 48.0, 32.0, 28.0, ARRAY['sirloin steak', 'broccoli', 'carrots', 'potatoes', 'olive oil']),
('dinner_002', 'Baked Salmon with Quinoa', 'Herb-crusted salmon with quinoa and asparagus', 'American', 'dinner', 520, 44.0, 42.0, 20.0, ARRAY['salmon', 'quinoa', 'asparagus', 'herbs', 'lemon']),
('dinner_003', 'Chicken Parmigiana', 'Breaded chicken with marinara and mozzarella', 'Italian', 'dinner', 640, 52.0, 48.0, 26.0, ARRAY['chicken breast', 'marinara sauce', 'mozzarella', 'pasta', 'parmesan']),
('dinner_004', 'Beef Tacos', 'Seasoned ground beef in hard shells with toppings', 'Mexican', 'dinner', 560, 36.0, 52.0, 24.0, ARRAY['ground beef', 'taco shells', 'cheese', 'lettuce', 'salsa', 'sour cream']),
('dinner_005', 'Stir-Fried Beef and Broccoli', 'Tender beef with broccoli in savory sauce', 'Asian', 'dinner', 480, 42.0, 38.0, 18.0, ARRAY['beef', 'broccoli', 'soy sauce', 'garlic', 'ginger', 'rice']),
('dinner_006', 'Lamb Kebabs with Rice', 'Grilled lamb skewers with seasoned rice', 'Mediterranean', 'dinner', 580, 44.0, 48.0, 22.0, ARRAY['lamb', 'rice', 'onions', 'peppers', 'yogurt sauce']),
('dinner_007', 'Roasted Chicken with Potatoes', 'Herb-roasted chicken quarters with potatoes', 'American', 'dinner', 620, 54.0, 44.0, 24.0, ARRAY['chicken', 'potatoes', 'carrots', 'herbs', 'olive oil']),
('dinner_008', 'Seafood Risotto', 'Creamy risotto with mixed seafood', 'Italian', 'dinner', 560, 32.0, 64.0, 18.0, ARRAY['arborio rice', 'shrimp', 'mussels', 'white wine', 'parmesan']),
('dinner_009', 'Chile Rellenos', 'Stuffed poblano peppers with cheese', 'Mexican', 'dinner', 520, 28.0, 42.0, 28.0, ARRAY['poblano peppers', 'cheese', 'eggs', 'tomato sauce', 'rice']),
('dinner_010', 'Peking Duck', 'Crispy duck with pancakes and hoisin sauce', 'Asian', 'dinner', 680, 42.0, 56.0, 32.0, ARRAY['duck', 'pancakes', 'hoisin sauce', 'cucumber', 'green onions']),
('dinner_011', 'Moussaka', 'Layered eggplant and meat casserole', 'Mediterranean', 'dinner', 580, 36.0, 42.0, 28.0, ARRAY['eggplant', 'ground beef', 'bechamel sauce', 'tomatoes', 'cheese']),
('dinner_012', 'Grilled Pork Chops', 'Marinated pork chops with sweet potato', 'American', 'dinner', 560, 46.0, 44.0, 20.0, ARRAY['pork chops', 'sweet potato', 'green beans', 'herbs']),
('dinner_013', 'Osso Buco', 'Braised veal shanks with vegetables', 'Italian', 'dinner', 620, 52.0, 36.0, 28.0, ARRAY['veal shanks', 'tomatoes', 'carrots', 'celery', 'white wine']),
('dinner_014', 'Chicken Mole', 'Chicken in rich chocolate-chili sauce', 'Mexican', 'dinner', 580, 44.0, 48.0, 24.0, ARRAY['chicken', 'mole sauce', 'rice', 'sesame seeds']),
('dinner_015', 'General Tso Chicken', 'Crispy chicken in sweet and spicy sauce', 'Asian', 'dinner', 640, 38.0, 72.0, 22.0, ARRAY['chicken', 'soy sauce', 'sugar', 'chili peppers', 'rice']),
('dinner_016', 'Greek Lamb Chops', 'Grilled lamb chops with lemon and herbs', 'Mediterranean', 'dinner', 560, 48.0, 24.0, 32.0, ARRAY['lamb chops', 'lemon', 'oregano', 'garlic', 'vegetables']),
('dinner_017', 'Meatloaf with Mashed Potatoes', 'Classic meatloaf with creamy mashed potatoes', 'American', 'dinner', 620, 42.0, 54.0, 26.0, ARRAY['ground beef', 'potatoes', 'onions', 'ketchup', 'herbs']),
('dinner_018', 'Eggplant Parmigiana', 'Breaded eggplant with marinara and cheese', 'Italian', 'dinner', 520, 24.0, 56.0, 22.0, ARRAY['eggplant', 'marinara sauce', 'mozzarella', 'parmesan', 'basil']),
('dinner_019', 'Shrimp Fajitas', 'Grilled shrimp with peppers and onions', 'Mexican', 'dinner', 480, 38.0, 48.0, 14.0, ARRAY['shrimp', 'tortillas', 'bell peppers', 'onions', 'lime']),
('dinner_020', 'Mongolian Beef', 'Tender beef in savory brown sauce', 'Asian', 'dinner', 560, 42.0, 52.0, 20.0, ARRAY['beef', 'soy sauce', 'brown sugar', 'green onions', 'rice']),
('dinner_021', 'Stuffed Bell Peppers', 'Peppers filled with ground beef and rice', 'Mediterranean', 'dinner', 480, 32.0, 48.0, 16.0, ARRAY['bell peppers', 'ground beef', 'rice', 'tomatoes', 'cheese']),
('dinner_022', 'Pot Roast', 'Slow-cooked beef roast with vegetables', 'American', 'dinner', 580, 52.0, 42.0, 20.0, ARRAY['beef roast', 'carrots', 'potatoes', 'onions', 'broth']),
('dinner_023', 'Chicken Cacciatore', 'Chicken braised with tomatoes and vegetables', 'Italian', 'dinner', 520, 46.0, 38.0, 18.0, ARRAY['chicken', 'tomatoes', 'peppers', 'onions', 'wine']),
('dinner_024', 'Carne Asada', 'Grilled marinated steak with sides', 'Mexican', 'dinner', 600, 48.0, 42.0, 26.0, ARRAY['steak', 'lime', 'cilantro', 'tortillas', 'salsa']),
('dinner_025', 'Thai Green Curry', 'Chicken in coconut curry with vegetables', 'Asian', 'dinner', 540, 36.0, 48.0, 24.0, ARRAY['chicken', 'coconut milk', 'green curry paste', 'vegetables', 'rice']),
('dinner_026', 'Mediterranean Sea Bass', 'Grilled sea bass with olives and tomatoes', 'Mediterranean', 'dinner', 480, 42.0, 28.0, 22.0, ARRAY['sea bass', 'olives', 'tomatoes', 'capers', 'olive oil']),
('dinner_027', 'Beef Stroganoff', 'Beef in creamy mushroom sauce over noodles', 'American', 'dinner', 620, 42.0, 56.0, 26.0, ARRAY['beef', 'mushrooms', 'sour cream', 'egg noodles', 'onions']),
('dinner_028', 'Veal Piccata', 'Veal cutlets in lemon-caper sauce', 'Italian', 'dinner', 520, 44.0, 32.0, 24.0, ARRAY['veal', 'lemon', 'capers', 'white wine', 'butter']),
('dinner_029', 'Pork Tamales', 'Corn masa with pork filling steamed in husks', 'Mexican', 'dinner', 560, 28.0, 64.0, 22.0, ARRAY['masa', 'pork', 'chili sauce', 'corn husks']),
('dinner_030', 'Korean BBQ Beef', 'Marinated beef grilled with kimchi', 'Asian', 'dinner', 580, 46.0, 42.0, 24.0, ARRAY['beef', 'soy sauce', 'sesame oil', 'kimchi', 'rice'])

-- SNACK MEALS (25 meals)
,('snack_001', 'Apple with Almond Butter', 'Sliced apple with natural almond butter', 'American', 'snack', 220, 6.0, 28.0, 10.0, ARRAY['apple', 'almond butter']),
('snack_002', 'Greek Yogurt with Honey', 'Plain Greek yogurt drizzled with honey', 'Mediterranean', 'snack', 180, 15.0, 24.0, 3.0, ARRAY['greek yogurt', 'honey']),
('snack_003', 'Hummus with Vegetables', 'Hummus served with carrot and celery sticks', 'Mediterranean', 'snack', 160, 6.0, 20.0, 7.0, ARRAY['hummus', 'carrots', 'celery', 'cucumbers']),
('snack_004', 'Protein Shake', 'Whey protein shake with banana', 'American', 'snack', 240, 30.0, 26.0, 3.0, ARRAY['protein powder', 'banana', 'almond milk']),
('snack_005', 'Trail Mix', 'Mixed nuts, seeds, and dried fruit', 'American', 'snack', 280, 8.0, 32.0, 16.0, ARRAY['almonds', 'cashews', 'raisins', 'dried cranberries', 'pumpkin seeds']),
('snack_006', 'Caprese Skewers', 'Cherry tomatoes, mozzarella, and basil on skewers', 'Italian', 'snack', 180, 12.0, 8.0, 12.0, ARRAY['cherry tomatoes', 'mozzarella', 'basil', 'olive oil']),
('snack_007', 'Guacamole with Chips', 'Fresh guacamole with tortilla chips', 'Mexican', 'snack', 240, 4.0, 28.0, 14.0, ARRAY['avocado', 'lime', 'tomatoes', 'tortilla chips']),
('snack_008', 'Edamame', 'Steamed soybeans with sea salt', 'Asian', 'snack', 190, 17.0, 16.0, 8.0, ARRAY['edamame', 'sea salt']),
('snack_009', 'Cottage Cheese with Fruit', 'Low-fat cottage cheese with fresh berries', 'American', 'snack', 200, 22.0, 24.0, 3.0, ARRAY['cottage cheese', 'strawberries', 'blueberries']),
('snack_010', 'Bruschetta', 'Toasted bread with tomato and basil topping', 'Italian', 'snack', 160, 6.0, 24.0, 5.0, ARRAY['bread', 'tomatoes', 'basil', 'garlic', 'olive oil']),
('snack_011', 'Cheese Quesadilla', 'Small tortilla with melted cheese', 'Mexican', 'snack', 280, 14.0, 28.0, 12.0, ARRAY['tortilla', 'cheese']),
('snack_012', 'Rice Crackers with Tuna', 'Rice crackers topped with tuna salad', 'Asian', 'snack', 220, 18.0, 26.0, 6.0, ARRAY['rice crackers', 'tuna', 'mayo', 'green onions']),
('snack_013', 'Peanut Butter Banana Toast', 'Whole grain toast with peanut butter and banana', 'American', 'snack', 300, 12.0, 42.0, 10.0, ARRAY['whole grain bread', 'peanut butter', 'banana']),
('snack_014', 'Olives and Cheese', 'Mixed olives with feta cheese cubes', 'Mediterranean', 'snack', 180, 8.0, 6.0, 14.0, ARRAY['olives', 'feta cheese', 'olive oil']),
('snack_015', 'Prosciutto and Melon', 'Cantaloupe wrapped in prosciutto', 'Italian', 'snack', 160, 12.0, 16.0, 6.0, ARRAY['prosciutto', 'cantaloupe']),
('snack_016', 'Salsa with Vegetables', 'Fresh salsa with bell pepper strips', 'Mexican', 'snack', 100, 2.0, 20.0, 2.0, ARRAY['tomatoes', 'onions', 'cilantro', 'bell peppers', 'lime']),
('snack_017', 'Miso Soup', 'Light miso soup with tofu', 'Asian', 'snack', 120, 8.0, 12.0, 4.0, ARRAY['miso paste', 'tofu', 'seaweed', 'green onions']),
('snack_018', 'Hard Boiled Eggs', 'Two hard boiled eggs with sea salt', 'American', 'snack', 140, 12.0, 2.0, 10.0, ARRAY['eggs', 'sea salt']),
('snack_019', 'Tzatziki with Pita', 'Greek yogurt dip with pita triangles', 'Mediterranean', 'snack', 200, 10.0, 28.0, 6.0, ARRAY['greek yogurt', 'cucumber', 'garlic', 'pita bread']),
('snack_020', 'Antipasto Plate', 'Italian meats and cheeses with olives', 'Italian', 'snack', 260, 18.0, 8.0, 18.0, ARRAY['salami', 'mozzarella', 'olives', 'peppers']),
('snack_021', 'Nachos with Cheese', 'Tortilla chips with melted cheese and jalapeños', 'Mexican', 'snack', 320, 12.0, 36.0, 16.0, ARRAY['tortilla chips', 'cheese', 'jalapeños', 'salsa']),
('snack_022', 'Spring Rolls', 'Fresh vegetable spring rolls with dipping sauce', 'Asian', 'snack', 180, 6.0, 32.0, 4.0, ARRAY['rice paper', 'vegetables', 'rice noodles', 'peanut sauce']),
('snack_023', 'Protein Balls', 'No-bake energy balls with oats and peanut butter', 'American', 'snack', 220, 10.0, 28.0, 9.0, ARRAY['oats', 'peanut butter', 'honey', 'chocolate chips']),
('snack_024', 'Stuffed Dates', 'Dates stuffed with goat cheese and almonds', 'Mediterranean', 'snack', 200, 6.0, 32.0, 7.0, ARRAY['dates', 'goat cheese', 'almonds']),
('snack_025', 'Arancini', 'Fried rice balls with mozzarella center', 'Italian', 'snack', 240, 10.0, 28.0, 10.0, ARRAY['rice', 'mozzarella', 'breadcrumbs', 'marinara sauce'])
;
